import type {
    Movie,
    News,
    UpcomingMovie,
    FeaturedNews,
    TvSeasons,
} from "./types";

// Add TV seasons data
export const tvSeasons: TvSeasons = {
    tv1: [
        {
            seasonNumber: 1,
            episodes: [
                {
                    episodeNumber: 1,
                    title: "Chapter One: The Vanishing of Will Byers",
                    description:
                        "On his way home from a friend's house, young Will sees something terrifying. Nearby, a sinister secret lurks in the depths of a government lab.",
                    duration: "48 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
                {
                    episodeNumber: 2,
                    title: "Chapter Two: The Weirdo on Maple Street",
                    description:
                        "Lucas, Mike and Dustin try to talk to the girl they found in the woods. Hopper questions an anxious Joyce about an unsettling phone call.",
                    duration: "55 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
                {
                    episodeNumber: 3,
                    title: "Chapter Three: Holly, Jolly",
                    description:
                        "An increasingly concerned Nancy looks for Barb and finds out what Jonathan's been up to. Joyce is convinced Will is trying to talk to her.",
                    duration: "51 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
                {
                    episodeNumber: 4,
                    title: "Chapter Four: The Body",
                    description:
                        "Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover. Nancy and Jonathan form an unlikely alliance.",
                    duration: "49 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
            ],
        },
        {
            seasonNumber: 2,
            episodes: [
                {
                    episodeNumber: 1,
                    title: "Chapter One: MADMAX",
                    description:
                        "As the town preps for Halloween, a high-scoring rival shakes things up at the arcade, and a skeptical Hopper inspects a field of rotting pumpkins.",
                    duration: "48 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
                {
                    episodeNumber: 2,
                    title: "Chapter Two: Trick or Treat, Freak",
                    description:
                        "After Will sees something terrible on trick-or-treat night, Mike wonders whether Eleven's still out there. Nancy wrestles with the truth about Barb.",
                    duration: "56 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
            ],
        },
    ],
    tv2: [
        {
            seasonNumber: 1,
            episodes: [
                {
                    episodeNumber: 1,
                    title: "Pilot",
                    description:
                        "Diagnosed with terminal lung cancer, chemistry teacher Walter White teams up with former student Jesse Pinkman to cook and sell crystal meth.",
                    duration: "58 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
                {
                    episodeNumber: 2,
                    title: "Cat's in the Bag...",
                    description:
                        "After their first drug deal goes terribly wrong, Walt and Jesse are forced to deal with a corpse and a prisoner. Meanwhile, Skyler grows suspicious.",
                    duration: "48 min",
                    imageUrl: "/placeholder.svg?height=300&width=500",
                    videoUrl: "#",
                },
            ],
        },
    ],
};

// Featured movies for the carousel
export const featuredMovies: Movie[] = [
    {
        id: "movie1",
        title: "The Dark Knight",
        description:
            "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        year: 2008,
        genre: ["Action"],
        duration: "2h 32m",
        rating: 9.0,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
        director: "Christopher Nolan",
        writers: "Jonathan Nolan, Christopher Nolan",
        studio: "Warner Bros.",
        language: "English",
        awards: "Won 2 Oscars. 157 wins & 163 nominations total",
        budget: 185000000,
        boxOffice: 1005973645,
        mpaaRating: "PG-13",
        filmingLocations: ["Chicago", "London", "Hong Kong"],
        type: "movie",
        cast: [
            {
                id: "cast1",
                name: "Christian Bale",
                character: "Bruce Wayne",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast2",
                name: "Heath Ledger",
                character: "Joker",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast3",
                name: "Aaron Eckhart",
                character: "Harvey Dent",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast4",
                name: "Michael Caine",
                character: "Alfred",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast5",
                name: "Maggie Gyllenhaal",
                character: "Rachel Dawes",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast6",
                name: "Gary Oldman",
                character: "Jim Gordon",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast7",
                name: "Morgan Freeman",
                character: "Lucius Fox",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast8",
                name: "Cillian Murphy",
                character: "Scarecrow",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
        ],
    },
    {
        id: "movie2",
        title: "Inception",
        description:
            "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        year: 2010,
        genre: ["Sci-Fi"],
        duration: "2h 28m",
        rating: 8.8,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
        director: "Christopher Nolan",
        writers: "Christopher Nolan",
        studio: "Warner Bros.",
        language: "English",
        awards: "Won 4 Oscars. 157 wins & 220 nominations total",
        budget: 160000000,
        boxOffice: 836836967,
        mpaaRating: "PG-13",
        filmingLocations: ["Los Angeles", "London", "Paris", "Morocco"],
        type: "movie",
        cast: [
            {
                id: "cast5",
                name: "Leonardo DiCaprio",
                character: "Cobb",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast6",
                name: "Joseph Gordon-Levitt",
                character: "Arthur",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast7",
                name: "Ellen Page",
                character: "Ariadne",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast8",
                name: "Tom Hardy",
                character: "Eames",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast9",
                name: "Ken Watanabe",
                character: "Saito",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast10",
                name: "Marion Cotillard",
                character: "Mal",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast11",
                name: "Cillian Murphy",
                character: "Robert Fischer",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast12",
                name: "Michael Caine",
                character: "Miles",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
        ],
    },
    {
        id: "movie3",
        title: "Interstellar",
        description:
            "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        year: 2014,
        genre: ["Sci-Fi"],
        duration: "2h 49m",
        rating: 8.6,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
        director: "Christopher Nolan",
        writers: "Jonathan Nolan, Christopher Nolan",
        studio: "Paramount Pictures",
        language: "English",
        awards: "Won 1 Oscar. 44 wins & 148 nominations total",
        budget: 165000000,
        boxOffice: 701729206,
        mpaaRating: "PG-13",
        filmingLocations: ["Iceland", "Canada", "Los Angeles"],
        type: "movie",
        cast: [
            {
                id: "cast9",
                name: "Matthew McConaughey",
                character: "Cooper",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast10",
                name: "Anne Hathaway",
                character: "Brand",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast11",
                name: "Jessica Chastain",
                character: "Murphy",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast12",
                name: "Michael Caine",
                character: "Professor Brand",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast13",
                name: "Mackenzie Foy",
                character: "Young Murphy",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast14",
                name: "John Lithgow",
                character: "Donald",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast15",
                name: "Timothée Chalamet",
                character: "Young Tom",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
            {
                id: "cast16",
                name: "Matt Damon",
                character: "Dr. Mann",
                photoUrl: "/placeholder.svg?height=200&width=200",
            },
        ],
    },
];

// Action movies
export const actionMovies: Movie[] = [
    {
        id: "action1",
        title: "John Wick",
        description:
            "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
        year: 2014,
        genre: ["Action"],
        duration: "1h 41m",
        rating: 7.4,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/2AUmvWm5ZDQ",
        director: "Chad Stahelski",
        writers: "Derek Kolstad",
        studio: "Summit Entertainment",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "action2",
        title: "Mad Max: Fury Road",
        description:
            "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
        year: 2015,
        genre: ["Action"],
        duration: "2h",
        rating: 8.1,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/hEJnMQG9ev8",
        director: "George Miller",
        writers: "George Miller, Brendan McCarthy, Nick Lathouris",
        studio: "Warner Bros.",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "action3",
        title: "Die Hard",
        description:
            "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.",
        year: 1988,
        genre: ["Action"],
        duration: "2h 12m",
        rating: 8.2,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/jaJuwKCmJbY",
        director: "John McTiernan",
        writers: "Jeb Stuart, Steven E. de Souza",
        studio: "20th Century Fox",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "action4",
        title: "The Matrix",
        description:
            "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        year: 1999,
        genre: ["Action"],
        duration: "2h 16m",
        rating: 8.7,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/vKQi3bBA1y8",
        director: "Lana Wachowski, Lilly Wachowski",
        writers: "Lana Wachowski, Lilly Wachowski",
        studio: "Warner Bros.",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "action5",
        title: "Mission: Impossible",
        description:
            "An American agent, under false suspicion of disloyalty, must discover and expose the real spy without the help of his organization.",
        year: 1996,
        genre: ["Action"],
        duration: "1h 50m",
        rating: 7.1,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/Ohws8y572KE",
        director: "Brian De Palma",
        writers: "Bruce Geller, David Koepp, Steven Zaillian",
        studio: "Paramount Pictures",
        language: "English",
        mpaaRating: "PG-13",
        type: "movie",
        cast: [],
    },
];

// TV Shows
export const tvShows: Movie[] = [
    {
        id: "tv1",
        title: "Stranger Things",
        description:
            "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
        year: 2016,
        genre: ["Sci-Fi"],
        duration: "4 Seasons",
        rating: 8.7,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/b9EkMc79ZSU",
        director: "The Duffer Brothers",
        studio: "Netflix",
        language: "English",
        mpaaRating: "TV-14",
        type: "tv",
        cast: [],
    },
    {
        id: "tv2",
        title: "Breaking Bad",
        description:
            "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
        year: 2008,
        genre: ["Drama"],
        duration: "5 Seasons",
        rating: 9.5,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
        director: "Vince Gilligan",
        studio: "AMC",
        language: "English",
        mpaaRating: "TV-MA",
        type: "tv",
        cast: [],
    },
    {
        id: "tv3",
        title: "Game of Thrones",
        description:
            "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        year: 2011,
        genre: ["Fantasy"],
        duration: "8 Seasons",
        rating: 9.2,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/KPLWWIOCOOQ",
        director: "David Benioff, D.B. Weiss",
        studio: "HBO",
        language: "English",
        mpaaRating: "TV-MA",
        type: "tv",
        cast: [],
    },
];

// Comedy movies
export const comedyMovies: Movie[] = [
    {
        id: "comedy1",
        title: "Superbad",
        description:
            "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
        year: 2007,
        genre: ["Comedy"],
        duration: "1h 53m",
        rating: 7.6,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/4eaZ_48ZYog",
        director: "Greg Mottola",
        writers: "Seth Rogen, Evan Goldberg",
        studio: "Columbia Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "comedy2",
        title: "The Hangover",
        description:
            "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
        year: 2009,
        genre: ["Comedy"],
        duration: "1h 40m",
        rating: 7.7,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/tcdUhdOlz9M",
        director: "Todd Phillips",
        writers: "Jon Lucas, Scott Moore",
        studio: "Warner Bros.",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "comedy3",
        title: "Bridesmaids",
        description:
            "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the life of an out-of-work pastry chef.",
        year: 2011,
        genre: ["Comedy"],
        duration: "2h 5m",
        rating: 6.8,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/FNppLrmdyug",
        director: "Paul Feig",
        writers: "Kristen Wiig, Annie Mumolo",
        studio: "Universal Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "comedy4",
        title: "Step Brothers",
        description:
            "Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.",
        year: 2008,
        genre: ["Comedy"],
        duration: "1h 38m",
        rating: 6.9,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/CewglxElBK0",
        director: "Adam McKay",
        writers: "Will Ferrell, Adam McKay",
        studio: "Columbia Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "comedy5",
        title: "Anchorman",
        description:
            "Ron Burgundy is San Diego's top-rated newsman in the male-dominated broadcasting of the 1970s, but that's all about to change.",
        year: 2004,
        genre: ["Comedy"],
        duration: "1h 34m",
        rating: 7.2,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/NJQ4qEWm9lU",
        director: "Adam McKay",
        writers: "Will Ferrell, Adam McKay",
        studio: "DreamWorks",
        language: "English",
        mpaaRating: "PG-13",
        type: "movie",
        cast: [],
    },
];

// Drama movies
export const dramaMovies: Movie[] = [
    {
        id: "drama1",
        title: "The Shawshank Redemption",
        description:
            "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        year: 1994,
        genre: ["Drama"],
        duration: "2h 22m",
        rating: 9.3,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/6hB3S9bIaco",
        director: "Frank Darabont",
        writers: "Stephen King, Frank Darabont",
        studio: "Columbia Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "drama2",
        title: "The Godfather",
        description:
            "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        year: 1972,
        genre: ["Drama"],
        duration: "2h 55m",
        rating: 9.2,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/sY1S34973zA",
        director: "Francis Ford Coppola",
        writers: "Mario Puzo, Francis Ford Coppola",
        studio: "Paramount Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "drama3",
        title: "Schindler's List",
        description:
            "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        year: 1993,
        genre: ["Drama"],
        duration: "3h 15m",
        rating: 8.9,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/gG22XNhtnoY",
        director: "Steven Spielberg",
        writers: "Thomas Keneally, Steven Zaillian",
        studio: "Universal Pictures",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
    {
        id: "drama4",
        title: "Forrest Gump",
        description:
            "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
        year: 1994,
        genre: ["Drama"],
        duration: "2h 22m",
        rating: 8.8,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/bLvqoHBptjg",
        director: "Robert Zemeckis",
        writers: "Winston Groom, Eric Roth",
        studio: "Paramount Pictures",
        language: "English",
        mpaaRating: "PG-13",
        type: "movie",
        cast: [],
    },
    {
        id: "drama5",
        title: "The Green Mile",
        description:
            "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        year: 1999,
        genre: ["Drama"],
        duration: "3h 9m",
        rating: 8.6,
        posterUrl: "/placeholder.svg?height=600&width=400",
        backdropUrl: "/placeholder.svg?height=720&width=1280",
        videoUrl: "#",
        trailerUrl: "https://www.youtube.com/embed/Ki4haFrqSrw",
        director: "Frank Darabont",
        writers: "Stephen King, Frank Darabont",
        studio: "Warner Bros.",
        language: "English",
        mpaaRating: "R",
        type: "movie",
        cast: [],
    },
];

// Combine all movies for the watch page
export const allMovies = [
    ...featuredMovies,
    ...actionMovies,
    ...comedyMovies,
    ...dramaMovies,
    ...tvShows,
];

// News items
export const newsItems: News[] = [
    {
        id: "news1",
        title: "New 'Dune: Part Two' Trailer Reveals Epic Scale of Denis Villeneuve's Sci-Fi Sequel",
        summary:
            "Warner Bros. has released a new trailer for 'Dune: Part Two,' showcasing the epic scale of Denis Villeneuve's highly anticipated sci-fi sequel. The film continues the adaptation of Frank Herbert's seminal novel with Timothée Chalamet returning as Paul Atreides.",
        date: "Mar 15, 2023",
        category: "Trailers",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 4,
    },
    {
        id: "news2",
        title: "Marvel Announces New Slate of Films for Phase 5 and 6",
        summary:
            "Marvel Studios has unveiled its ambitious lineup for Phases 5 and 6 of the Marvel Cinematic Universe, including new Avengers films. Kevin Feige revealed the roadmap at San Diego Comic-Con, confirming the next saga will be called 'The Multiverse Saga.'",
        date: "Mar 10, 2023",
        category: "Marvel",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 5,
    },
    {
        id: "news3",
        title: "Christopher Nolan's Next Film Set for Summer 2025 Release",
        summary:
            "Universal Pictures has announced that Christopher Nolan's mysterious new project will hit theaters in July 2025. Details about the plot remain tightly under wraps, but sources indicate it will be another original concept from the acclaimed director.",
        date: "Mar 5, 2023",
        category: "Production",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 3,
    },
    {
        id: "news4",
        title: "James Cameron Confirms 'Avatar 3' Is on Track for 2025 Release",
        summary:
            "Director James Cameron has confirmed that 'Avatar 3' is progressing well in post-production and will meet its scheduled December 2025 release date. The filmmaker also teased that the third installment will introduce a new Na'vi clan with a unique relationship to fire.",
        date: "Feb 28, 2023",
        category: "Production",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 4,
    },
    {
        id: "news5",
        title: "Joaquin Phoenix and Lady Gaga's 'Joker: Folie à Deux' First Look Released",
        summary:
            "Warner Bros. has released the first official images from the highly anticipated 'Joker' sequel, featuring Joaquin Phoenix reprising his Oscar-winning role alongside Lady Gaga as Harley Quinn. The musical psychological thriller is set to release in October 2024.",
        date: "Feb 20, 2023",
        category: "First Look",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 6,
    },
    {
        id: "news6",
        title: "Streaming Wars Heat Up as New Platforms Announce Exclusive Content",
        summary:
            "The competition among streaming services intensifies as several platforms announce major exclusive content deals. Industry analysts predict consolidation in the market as viewers become increasingly selective about their subscription choices.",
        date: "Feb 15, 2023",
        category: "Streaming",
        imageUrl: "/placeholder.svg?height=400&width=600",
        readTime: 5,
    },
];

// Featured News
export const featuredNews: FeaturedNews = {
    id: "featured1",
    title: "The Evolution of Cinema: How Streaming is Changing the Movie Industry",
    summary:
        "As streaming platforms continue to dominate the entertainment landscape, traditional movie studios are adapting their release strategies. This comprehensive analysis explores how the shift is affecting everything from production budgets to award shows, and what it means for the future of cinema.",
    date: "Mar 20, 2023",
    category: "Industry",
    imageUrl: "/placeholder.svg?height=800&width=1200",
    readTime: 12,
    relatedNews: [
        {
            title: "Major Studios Announce Direct-to-Streaming Release Strategy for 2024",
            category: "Business",
            date: "Mar 18, 2023",
            imageUrl: "/placeholder.svg?height=200&width=200",
        },
        {
            title: "Independent Filmmakers Find New Audience Through Streaming Platforms",
            category: "Indie",
            date: "Mar 15, 2023",
            imageUrl: "/placeholder.svg?height=200&width=200",
        },
        {
            title: "Theater Chains Innovate with Premium Experiences to Combat Streaming Trend",
            category: "Exhibition",
            date: "Mar 12, 2023",
            imageUrl: "/placeholder.svg?height=200&width=200",
        },
    ],
};

// Upcoming movies
export const upcomingMovies: UpcomingMovie[] = [
    {
        id: "upcoming1",
        title: "Avatar 3",
        description:
            "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora.",
        releaseDate: "Dec 20, 2024",
        imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
        id: "upcoming2",
        title: "Mission: Impossible 8",
        description:
            "Ethan Hunt returns in the eighth installment of the Mission: Impossible franchise.",
        releaseDate: "Jun 28, 2024",
        imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
        id: "upcoming3",
        title: "Gladiator II",
        description:
            "The sequel to Ridley Scott's 2000 historical epic follows a new character in ancient Rome.",
        releaseDate: "Nov 22, 2024",
        imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
        id: "upcoming4",
        title: "Furiosa: A Mad Max Saga",
        description:
            "The origin story of renegade warrior Furiosa before she teamed up with Mad Max in 'Fury Road'.",
        releaseDate: "May 24, 2024",
        imageUrl: "/placeholder.svg?height=400&width=600",
    },
];
